trunk/ (antanas@kurmis) Updating help messages to the bash and sh scripts. Adding '--options' option. Modifying 'check_options_descriptions.sh' tests to ignore '--options' option, since it is not supposed to be described in the options.
git-svn-id: svn://cod.ibt.lt/cod-tools/trunk@4207 04be6746-3802-0410-999d-98508da1e98c

diff --git a/scripts/cif_cod_deposit b/scripts/cif_cod_deposit
--- a/scripts/cif_cod_deposit
+++ b/scripts/cif_cod_deposit
@@ -6,10 +6,10 @@
 #$URL$
 #------------------------------------------------------------------------------
 #*
-#  Deposit CIFs into COD database using CGI deposition interface.
+# Deposit CIFs into COD database using CGI deposition interface.
 #
 # USAGE:
-#    $0 structure1.cif [structure2.cif ...]
+#    $0 --options structure1.cif structure*.cif
 #**
 
 TMP_DIR="${TMPDIR}"
@@ -62,129 +62,130 @@ setvar CIF_HEADER = ''
 
 curl=curl
 
-#** OPTIONS:
+#* OPTIONS:
+#*
+#*  -c, --config config-file-with-password.cfg
+#*      Specify which file holds depostor user name and
+#*      password (default: ~/.cod_deposit.cfg).
+#*
+#*  -h, --host  test.crystallography.net
+#*      Specify host to commit structrues to.
+#*
+#*  -p, --path  cgi-bin/cif-deposit.pl
+#*      Specify script path within the host to use for structure upload.
+#*
+#*  -u, --url  http://test.crystallography.net/cgi-bin/cif-deposit.pl
+#*      Specify the full URL to use for structure uploading (default:
+#*      combine --host and --path values using http:// protocol and /).
+#*
+#*  -d, --deposition-type published
+#*      Specify the deposition type under which the structure is to be 
+#*      deposited (default 'published').
+#*
+#*  -s, --separate-outputs folder-to-put-deposition-outputs/
+#*      Specify a folder to put deposition output for each deposited file.
+#*
+#*  -r, --read-stdin
+#*      Read list of CIF and Fobs file names from the standard input in
+#*      format
+#*      <CIF file> [<Fobs file> ]*
+#*      for example:
+#*      Ice.cif
+#*      bi5014sup1.cif all.hkl
+#*      bi5005sup1.cif bi50051sup2.hkl bi50052sup3.hkl
+#*
+#*   --cif "input1.cif input*.cif"
+#*      Specify a list of CIF files to be deposited.
+#*
+#*  --add-cif "input1.cif input*.cif"
+#*      Specify additional CIF files to be deposited.
+#*
+#*  --clear-cif
+#*      Clear the list of CIF files to be deposited.
+#*
+#*  --hkl, --fobs
+#*      Specify a list of Fobs files to be deposited.
+#*
+#*  --add-hkl, --add-fobs
+#*      Specify additional Fobs files to be deposited.
+#*
+#*  --clear-hkl, --clear-fobs
+#*      Clear the list of Fobs files to be deposited.
+#*
+#*  --replace
+#*      Specify that given files are replacements for previously
+#*      deposited data.
+#*
+#*  --release-data
+#*      Specify that given files were previously deposited as
+#*      prepublication material and should be now released into
+#*      the public domain.
+#*
+#*  --log-message, --log-msg
+#*      Specify log message for redeposited structures.
+#*
+#*  --script
+#*      Do not deposit, print the commands to be executed on deposition
+#*      instead.
+#*
+#*  --run
+#*      Enable the execution of deposition commands instead of simply
+#*      printing them (default).
+#*
+#*  --strict,
+#*  --no-ignore-unpaired-datablocks, --dont-ignore-unpaired-datablocks
+#*      Stop the deposition if any CIF datablock can not be paired to
+#*      any Fobs datablocks (provided that any unpaired datablocks
+#*      exist). Default option.
+#*
+#*  --silent, --ignore-unpaired-datablocks
+#*      Ignore unpaired CIF and Fobs datablocks.
+#*
+#*  --require-only-doi
+#*      Do not require any other bibliographic information to be
+#*      present if CIF datablock contains resolvable DOI.
+#*
+#*  --require-full-bibliography
+#*      Require all bibliographic information to be present in submitted
+#*      CIF file. Default option.
+#*
+#*  --use-wipe, --dont-use-wipe, --use-rm
+#*      Specifies whether to use 'wipe' comand (if present) or 'rm'
+#*      command to remove temporary password files.
+#*
+#*  --common-cif-header      Use a standard COD CIF header (default).
+#*  --iucr-cif-header        Use a COD CIF header agreed with IUCr.
+#*  --amcsd-cif-header       Use a COD CIF header agreed with R.D.
+#*  --crystaleye-cif-header  Use a COD CIF header agreed with P.M.-R.
+#*
+#*  --print-timestamps
+#*      Print timestamps to STDOUT at the start and end of each CIF
+#*      file depostion.
+#*
+#*  --no-print-timestamps, --dont-print-timestamps
+#*      Do not print timestamps to STDOUT at the start and end of
+#*      each CIF file depostion.
+#*
+#*  -P, --progress
+#*      Ask cif-deposit.pl to report progress of the deposition.
+#*
+#*  -P-, --no-progress
+#*      Silence cif-deposit.pl deposition progress report messages.
+#*
+#*  --output-mode html
+#*      Specify the output mode (from "html" and "stdout").
+#*
+#*  -D, --debug
+#*      Request output of the progress information from cif-deposit.pl to the
+#*      HTTP server log.
+#*
+#*  -D-, --no-debug
+#*      Disable the output of the progress information from cif-deposit.pl
+#*      to the HTTP server log (default)
+#*
+#*  --help, --usage
+#*      Print a short help message (this message) and exit.
 #**
-#**  -c, --config config-file-with-password.cfg
-#**      Specify which file holds depostor user name and
-#**      password (default: ~/.cod_deposit.cfg).
-#**
-#**  -h, --host  test.crystallography.net
-#**      Specify host to commit structrues to.
-#**
-#**  -p, --path  cgi-bin/cif-deposit.pl
-#**      Specify script path within the host to use for structure upload.
-#**
-#**  -u, --url  http://test.crystallography.net/cgi-bin/cif-deposit.pl
-#**      Specify the full URL to use for structure uploading (default:
-#**      combine --host and --path values using http:// protocol and /).
-#**
-#**  -d, --deposition-type published
-#**      Specify the deposition type under which the structure is to be 
-#**      deposited (default 'published').
-#**
-#**  -s, --separate-outputs folder-to-put-deposition-outputs/
-#**      Specify a folder to put deposition output for each deposited file.
-#**
-#**  -r, --read-stdin
-#**      Read list of CIF and Fobs file names from the standard input in
-#**      format
-#**      <CIF file> [<Fobs file> ]*
-#**      for example:
-#**      Ice.cif
-#**      bi5014sup1.cif all.hkl
-#**      bi5005sup1.cif bi50051sup2.hkl bi50052sup3.hkl
-#**
-#**   --cif "input1.cif input*.cif"
-#**      Specify a list of CIF files to be deposited.
-#**
-#**  --add-cif "input1.cif input*.cif"
-#**      Specify additional CIF files to be deposited.
-#**
-#**  --clear-cif
-#**      Clear the list of CIF files to be deposited.
-#**
-#**  --hkl, --fobs
-#**      Specify a list of Fobs files to be deposited.
-#**
-#**  --add-hkl, --add-fobs
-#**      Specify additional Fobs files to be deposited.
-#**
-#**  --clear-hkl, --clear-fobs
-#**      Clear the list of Fobs files to be deposited.
-#**
-#**  --replace
-#**      Specify that given files are replacements for previously
-#**      deposited data.
-#**
-#**  --release-data
-#**      Specify that given files were previously deposited as
-#**      prepublication material and should be now released into
-#**      the public domain.
-#**
-#**  --log-message, --log-msg
-#**      Specify log message for redeposited structures.
-#**
-#**  --script
-#**      Do not deposit, print the commands to be executed on deposition
-#**      instead.
-#**
-#**  --run
-#**      Enable the execution of deposition commands instead of simply
-#**      printing them (default).
-#**
-#**  --strict,
-#**  --no-ignore-unpaired-datablocks, --dont-ignore-unpaired-datablocks
-#**      Stop the deposition if any CIF datablock can not be paired to
-#**      any Fobs datablocks (provided that any unpaired datablocks
-#**      exist). Default option.
-#**
-#**  --silent, --ignore-unpaired-datablocks
-#**      Ignore unpaired CIF and Fobs datablocks.
-#**
-#**  --require-only-doi
-#**      Do not require any other bibliographic information to be
-#**      present if CIF datablock contains resolvable DOI.
-#**
-#**  --require-full-bibliography
-#**      Require all bibliographic information to be present in submitted
-#**      CIF file. Default option.
-#**
-#**  --use-wipe, --dont-use-wipe, --use-rm
-#**      Specifies whether to use 'wipe' comand (if present) or 'rm'
-#**      command to remove temporary password files.
-#**
-#**  --common-cif-header      Use a standard COD CIF header (default).
-#**  --iucr-cif-header        Use a COD CIF header agreed with IUCr.
-#**  --amcsd-cif-header       Use a COD CIF header agreed with R.D.
-#**  --crystaleye-cif-header  Use a COD CIF header agreed with P.M.-R.
-#**
-#**  --print-timestamps
-#**      Print timestamps to STDOUT at the start and end of each CIF
-#**      file depostion.
-#**
-#**  --no-print-timestamps, --dont-print-timestamps
-#**      Do not print timestamps to STDOUT at the start and end of
-#**      each CIF file depostion.
-#**
-#**  -P, --progress
-#**      Ask cif-deposit.pl to report progress of the deposition.
-#**
-#**  -P-, --no-progress
-#**      Silence cif-deposit.pl deposition progress report messages.
-#**
-#**  --output-mode html
-#**      Specify the output mode (from "html" and "stdout").
-#**
-#**  -D, --debug
-#**      Request output of the progress information from cif-deposit.pl to the
-#**      HTTP server log.
-#**
-#**  -D-, --no-debug
-#**      Disable the output of the progress information from cif-deposit.pl
-#**      to the HTTP server log (default)
-#**
-#**  --help, --usage
-#**      Print a short help message (this message) and exit.
 while [ $# -gt 0 ]
 do
   case $1 in
@@ -329,6 +330,17 @@ do
       --run|--ru|--r)
           curl=curl
           ;;
+      --options|--option|--optio|--opti|--opt|--op|--o)
+          echo "`basename $0`:: The '--options' option is a placehoder."
+          echo "`basename $0`:: It should be replaced by one of the following options:"
+          awk '/#\* OPTIONS:/,/#\*\*/ {
+                  sub("OPTIONS:", ""); \
+                  sub("^ *#[*]?[*]?", ""); \
+                  gsub("\\$0","'$0'"); \
+                  print $0
+              }' $0
+          exit
+          ;;
       --help|--hel|--he|--h|--usage)
           gawk '/^#\*/,/^#\*\*/ {
                   sub("^ *#[*]?[*]?", ""); \
@@ -337,7 +349,7 @@ do
               }' $0
           exit
           ;;
-      -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
+      -*) echo "`basename $0`:: ERROR, unknown option '$1'." >&2 ; exit 1 ;;
       *)  CIF_FILES="$CIF_FILES $1" ;;
     esac
     shift
@@ -348,8 +360,8 @@ eval set -- "${CIF_FILES}"
 
 if [ "$(echo ${CIF_FILES} | wc -w)" -gt 1 -a -n "${HKL_FILES}" ]
 then
-    echo "`basename $0`: can not accept Fobs files together with \
-more than one CIF file" >&2
+    echo "`basename $0`:: ERROR, cannot accept Fobs files together with \
+more than one CIF file." >&2
     exit 1
 fi
 
@@ -505,7 +517,7 @@ cat ${TMP_DEPOSIT_LIST} | \
         HKL=$(echo "$line" | cut -d "${SEPARATOR}" -f 2-)
         if [ ${TIMESTAMPS} = true ]
         then
-            echo ${BASENAME}: ${CIF}: NOTE: Deposition started at $(date)
+            echo ${BASENAME}: ${CIF}: NOTE, deposition started at $(date).
         fi
         CIF_ARG="-F cif=@${CIF};filename=$(basename ${CIF})"
         HKL_ARG=""
@@ -548,7 +560,7 @@ cat ${TMP_DEPOSIT_LIST} | \
             | eval ${DEPOSIT_LOGGER}
         if [ ${TIMESTAMPS} = true ]
         then
-            echo ${BASENAME}: ${CIF}: NOTE: Deposition finished at $(date)
+            echo ${BASENAME}: ${CIF}: NOTE, deposition finished at $(date).
         fi
     done
 
diff --git a/scripts/codcif2sdf b/scripts/codcif2sdf
--- a/scripts/codcif2sdf
+++ b/scripts/codcif2sdf
@@ -35,8 +35,11 @@ setvar IGNORE_BUMPS_OPT = ""
 #*  -i, --ignore-bumps
 #*      Ignore atomic bumps while running cif_molecule.
 #*
-#*  --tmp-dir /tmp    Use the specified trmporary directory (default is /tmp).
-#*  --help            Print short help message (this message) and exit.
+#*  --tmp-dir /tmp
+#*      Use the specified trmporary directory (default is /tmp).
+#*
+#*  --help, --usage
+#*      Print a short help message (this message) and exit.
 #**
 while [ $# -gt 0 ]
 do
@@ -49,15 +52,26 @@ do
           TMP_DIR="$2"
           shift
           ;;
-      --help|--hel|--he|--h)
-            awk '/#\*/,/#\*\*/ {
-                    sub("^ *#[*]?[*]?", ""); \
-                    gsub("\\$0","'$0'"); \
-                    print $0
-                }' $0
-	    exit
-	    ;;      
-      -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
+      --options|--option|--optio|--opti|--opt|--op|--o)
+          echo "`basename $0`:: The '--options' option is a placehoder."
+          echo "`basename $0`:: It should be replaced by one of the following options:"
+          awk '/#\* OPTIONS:/,/#\*\*/ {
+                  sub("OPTIONS:", ""); \
+                  sub("^ *#[*]?[*]?", ""); \
+                  gsub("\\$0","'$0'"); \
+                  print $0
+              }' $0
+          exit
+          ;;
+      --help|--hel|--he|--h|--usage)
+          awk '/#\*/,/#\*\*/ {
+                  sub("^ *#[*]?[*]?", ""); \
+                  gsub("\\$0","'$0'"); \
+                  print $0
+              }' $0
+          exit
+          ;;
+      -*) echo "`basename $0`:: ERROR, unknown option '$1'." >&2 ; exit 1 ;;
       *)  FILES="$FILES '$1'" ;;
     esac
     shift
@@ -83,13 +97,13 @@ for CIF in ${1+"$@"}
 do
     if [ ${CIF} = "-" ]
     then
-        echo $0: reading CIF from STDIN... >&2
+        echo $0: $CIF: reading CIF from STDIN... >&2
         cat > ${TMP_CIF}
         CIF=${TMP_CIF}
     else
         if [ ! -e ${CIF} ]
         then
-            echo $0:$CIF: file "'${CIF}'" does not exist >&2
+            echo $0: $CIF: file does not exist. >&2
             continue
         fi
     fi
diff --git a/scripts/molcif2sdf b/scripts/molcif2sdf
--- a/scripts/molcif2sdf
+++ b/scripts/molcif2sdf
@@ -35,8 +35,11 @@ setvar COD_CIF = ""
 #*  -C, --cod-cif 1000000.cif
 #*      Provide the original COD CIF to extract structure metadata.
 #*
-#*  --tmp-dir /tmp    Use the specified trmporary directory (default is /tmp)
-#*  --help            Print short help message (this message) and exit,
+#*  --tmp-dir /tmp
+#*      Use the specified trmporary directory (default is /tmp).
+#*
+#*  --help, --usage
+#*      Print a short help message (this message) and exit.
 #**
 while [ $# -gt 0 ]
 do
@@ -49,15 +52,26 @@ do
           TMP_DIR="$2"
           shift
           ;;
-      --help|--hel|--he|--h)
-            awk '/#\*/,/#\*\*/ {
-                    sub("^ *#[*]?[*]?", ""); \
-                    gsub("\\$0","'$0'"); \
-                    print $0
-                }' $0
-            exit
-            ;;
-      -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
+      --options|--option|--optio|--opti|--opt|--op|--o)
+          echo "`basename $0`:: The '--options' option is a placehoder."
+          echo "`basename $0`:: It should be replaced by one of the following options:"
+          awk '/#\* OPTIONS:/,/#\*\*/ {
+                  sub("OPTIONS:", ""); \
+                  sub("^ *#[*]?[*]?", ""); \
+                  gsub("\\$0","'$0'"); \
+                  print $0
+              }' $0
+          exit
+          ;;
+      --help|--hel|--he|--h|--usage)
+          awk '/#\*/,/#\*\*/ {
+                  sub("^ *#[*]?[*]?", ""); \
+                  gsub("\\$0","'$0'"); \
+                  print $0
+              }' $0
+          exit
+          ;;
+      -*) echo "`basename $0`:: ERROR, unknown option '$1'." >&2 ; exit 1 ;;
       *)  FILES="$FILES '$1'" ;;
     esac
     shift
