trunk/ (antanas@kurmis) Updating help messages to the bash and sh scripts. Adding '--options' option. Modifying 'check_options_descriptions.sh' tests to ignore '--options' option, since it is not supposed to be described in the options.
git-svn-id: svn://www.crystallography.net/cod-tools/trunk@4207 04be6746-3802-0410-999d-98508da1e98c

diff --git a/scripts/ungrepciftag b/scripts/ungrepciftag
--- a/scripts/ungrepciftag
+++ b/scripts/ungrepciftag
@@ -30,7 +30,7 @@ do
               }' $0
           exit
           ;;
-      -+) echo "`basename $0`:: ERROR, unknown option $1" >&2 ; exit 1 ;;
+      -?*) echo "`basename $0`:: ERROR, unknown option '$1'." >&2 ; exit 1 ;;
       *)
           if [ -z "$PATTERN" ];
           then
