trunk/: Adding rules into the makefiles/Makefile-perl-multiscript-tests file to run those test cases that have only an .opt file, and no .inp file. This permits, among others, testing how scripts read data from STDIN.
git-svn-id: svn://cod.ibt.lt/cod-tools/trunk@751 04be6746-3802-0410-999d-98508da1e98c

diff --git a/makefiles/Makefile-perl-multiscript-tests b/makefiles/Makefile-perl-multiscript-tests
--- a/makefiles/Makefile-perl-multiscript-tests
+++ b/makefiles/Makefile-perl-multiscript-tests
@@ -62,10 +62,13 @@ DIFF_FILES = ${patsubst ${TEST_DIR}/%${EXT},${OUTPUT_DIR}/%.diff,${TEST_FILES}}
 
 
 INP            = .inp
+OPT            = .opt
 SCRIPT_TST_DIR = ./tests
-SCRIPT_TESTS   = ${wildcard ${SCRIPT_TST_DIR}/*${INP}}
-SCRIPT_OUTPUTS = ${SCRIPT_TESTS:${SCRIPT_TST_DIR}/%${INP}=${OUTPUT_DIR}/%.out}
-SCRIPT_DIFFS   = ${SCRIPT_TESTS:${SCRIPT_TST_DIR}/%${INP}=${OUTPUT_DIR}/%.diff}
+SCRIPT_INPUTS  = ${wildcard ${SCRIPT_TST_DIR}/*${INP}}
+SCRIPT_OPTIONS = ${wildcard ${SCRIPT_TST_DIR}/*${OPT}}
+SCRIPT_TESTS   = $(sort ${SCRIPT_INPUTS:%${INP}=%} ${SCRIPT_OPTIONS:%${OPT}=%})
+SCRIPT_OUTPUTS = ${SCRIPT_TESTS:${SCRIPT_TST_DIR}/%=${OUTPUT_DIR}/%.out}
+SCRIPT_DIFFS   = ${SCRIPT_TESTS:${SCRIPT_TST_DIR}/%=${OUTPUT_DIR}/%.diff}
 
 #
 # Outputs and tests from the shell-driven tests
@@ -101,7 +104,7 @@ ${OUTPUT_DIR}/%.out: ${TARGET} ${TEST_DIR}/%${EXT}
 
 # Rules to run script-specific tests
 
-${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%.opt \
+${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%${OPT} \
                       ${SCRIPT_FILES} ${YAPP_MODULES}
 	-@printf "%-30s " "$<:" ; \
 	./$(shell echo $* | sed -e 's/_[0-9]*$$//') \
@@ -117,7 +120,15 @@ ${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_FILES} ${YAPP_MODULES}
 	| diff ${OUTPUT_DIR}/$*.out - > $@ ; \
 	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
 
-${OUTPUT_DIR}/%.out: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%.opt ${YAPP_MODULES}
+${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${OPT} ${SCRIPT_FILES} ${YAPP_MODULES}
+	-@printf "%-30s " "$<:" ; \
+	./$(shell echo $* | sed -e 's/_[0-9]*$$//') \
+	     $(shell grep -v '^#' ${word 1, $^}) \
+	2>&1 \
+	| diff ${OUTPUT_DIR}/$*.out - > $@ ; \
+	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
+
+${OUTPUT_DIR}/%.out: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%${OPT} ${YAPP_MODULES}
 	-@test -f $@ || echo "$@:"
 	-@test -f $@ || \
 	./$(shell echo $* | sed -e 's/_[0-9]*$$//') \
@@ -132,6 +143,15 @@ ${OUTPUT_DIR}/%.out: ${SCRIPT_TST_DIR}/%${INP} ${YAPP_MODULES}
 	-@test -f $@ || \
 	./$(shell echo $* | sed -e 's/_[0-9]*$$//') \
 	    $< \
+	2>&1 \
+	| tee $@
+	-@touch $@
+
+${OUTPUT_DIR}/%.out: ${SCRIPT_TST_DIR}/%${OPT} ${YAPP_MODULES}
+	-@test -f $@ || echo "$@:"
+	-@test -f $@ || \
+	./$(shell echo $* | sed -e 's/_[0-9]*$$//') \
+	    $(shell grep -v '^#' ${word 1, $^}) \
 	2>&1 \
 	| tee $@
 	-@touch $@
