Merging changes from the branches/makefiles into trunk/makefiles:
svn merge -r235:249 ../../branches/makefiles/Makefile-YAPP-test

This addd a possibility of shell-driven tests and fixes some
dependency bugs.


git-svn-id: svn://cod.ibt.lt/cod-tools/trunk@277 04be6746-3802-0410-999d-98508da1e98c

diff --git a/makefiles/Makefile-YAPP-test b/makefiles/Makefile-YAPP-test
--- a/makefiles/Makefile-YAPP-test
+++ b/makefiles/Makefile-YAPP-test
@@ -14,7 +14,7 @@ DIFF_FILES = ${TEST_FILES:${TEST_DIR}/%.inp=${OUTP_DIR}/%.diff}
 OUTP_FILES = ${TEST_FILES:${TEST_DIR}/%.inp=${OUTP_DIR}/%.out}
 
 .PRECIOUS: %.pm
-.PHONY: all clean cleanAll distclean test tests out outputs
+.PHONY: all clean cleanAll distclean test tests alltests out outputs
 .PHONY: run
 
 ## all: ${PM_FILES}
@@ -30,18 +30,20 @@ run: ${PM_FILES} ${WORK_TESTS}
 	); \
 	done
 
-test tests: ${DIFF_FILES}
-
-out outputs: ${OUTP_FILES}
+tests alltests: test shtest
 
 #------------------------------------------------------------------------------
+
+test: ${DIFF_FILES}
+
+out outputs: ${OUTP_FILES}
 
 %.pm: %.yp
 	yapp -v -o $@ $<
 
 ${OUTP_DIR}/%.diff: ${TEST_MODULE} ${TEST_DIR}/%.inp
 	-@printf "%-30s " "$*:" ; \
-     perl -e 'use ${TEST_MODULE:%.pm=%}; my $$p=new ${TEST_MODULE:%.pm=%}; $$p->Run' \
+	perl -e 'use ${TEST_MODULE:%.pm=%}; my $$p=new ${TEST_MODULE:%.pm=%}; $$p->Run' \
          < ${word 2, $^} 2>&1 \
      | diff ${OUTP_DIR}/$*.out - \
      > $@ ; \
@@ -49,8 +51,41 @@ ${OUTP_DIR}/%.diff: ${TEST_MODULE} ${TEST_DIR}/%.inp
 
 ${OUTP_DIR}/%.out: ${TEST_MODULE} ${TEST_DIR}/%.inp
 	-@test -f $@ || echo "$@:"
-	-@test -f $@ || perl $< < ${word 2, $^} 2>&1 | tee $@
+	-@test -f $@ || \
+	perl -e 'use ${TEST_MODULE:%.pm=%}; my $$p=new ${TEST_MODULE:%.pm=%}; $$p->Run' \
+	< ${word 2, $^} 2>&1 \
+	| tee $@
 	-@touch $@
+
+#------------------------------------------------------------------------------
+
+.PHONY: shtests
+
+#
+# Outputs and tests for the shell-driven tests:
+#
+
+SHELL_TSTDIR = ./shtests
+SHELL_OUTDIR = ./shoutputs
+
+SHELL_TESTS   = ${wildcard ${SHELL_TSTDIR}/*.sh}
+SHELL_BASES   = ${notdir ${SHELL_TESTS}}
+SHELL_OUTPUTS = ${addprefix ${SHELL_OUTDIR}/, ${SHELL_BASES:%.sh=%.out}}
+SHELL_DIFFS   = ${addprefix ${SHELL_OUTDIR}/, ${SHELL_BASES:%.sh=%.diff}}
+
+shoutputs shout: ${SHELL_OUTPUTS}
+
+shtest shtests: ${SHELL_DIFFS}
+
+${SHELL_OUTDIR}/%.out: ${SHELL_TSTDIR}/%.sh ${TEST_MODULE}
+	-@test -f $@ || echo "$@:"
+	-@test -f $@ || $< ./${TEST_MODULE} 2>&1 | tee $@
+	-@touch $@
+
+${SHELL_OUTDIR}/%.diff: ${SHELL_TSTDIR}/%.sh ${TEST_MODULE}
+	-@printf "%-30s " "$*:" ; \
+	$< ./${TEST_MODULE} 2>&1 | diff ${SHELL_OUTDIR}/$*.out - > $@ ; \
+	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
 
 #------------------------------------------------------------------------------
 
@@ -60,11 +95,15 @@ listdiff: # test
 	@-( test -d ${OUTP_DIR} && \
 	    ls -l ${OUTP_DIR}/*.diff | awk '{if( $$5 > 0 ) print}' ) || \
 	    true
+	@-( test -d ${SHELL_OUTDIR} && \
+	    ls -l ${SHELL_OUTDIR}/*.diff | awk '{if( $$5 > 0 ) print}' ) || \
+	    true
 
 #------------------------------------------------------------------------------
 
 clean:
 	rm -f ${DIFF_FILES}
+	rm -f ${SHELL_DIFFS}
 
 distclean cleanAll: clean
 	rm -f ${PM_FILES}
