trunk/ Adding test case skipping mechanism (via *.chk files) for input/option-based test cases, found under tests/cases/. The mechanism is identical to the one, used for Shell test cases.
git-svn-id: svn://www.crystallography.net/cod-tools/trunk@4806 04be6746-3802-0410-999d-98508da1e98c

diff --git a/makefiles/Makefile-perl-multiscript-tests b/makefiles/Makefile-perl-multiscript-tests
--- a/makefiles/Makefile-perl-multiscript-tests
+++ b/makefiles/Makefile-perl-multiscript-tests
@@ -179,30 +179,45 @@ ${TST_DIFFS} ${SCRIPT_DIFFS}: ${LOCAL_LIB_FILES}
 ${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%${OPT} \
                       ${COMPILED_MODULES}
 	-@printf "%-30s " "$<:" ; \
+	if [ ! -f ${SCRIPT_TST_DIR}/$*.chk ] || ${SCRIPT_TST_DIR}/$*.chk; \
+	then \
 	( ${SCRIPT_DIR}/$(shell echo $* | sed -e 's/_[0-9]*$$//') \
 	    $(shell grep -v '^#' ${word 2, $^}) \
 	    $< \
 	| ${buffer_output} ) 2>&1 \
 	| ${filter_perl_messages} \
 	| diff ${OUTPUT_DIR}/$*.out - > $@ ; \
-	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
+	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi \
+	else \
+	touch $@; \
+	fi
 
 ${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${INP} ${COMPILED_MODULES}
 	-@printf "%-30s " "$<:" ; \
+	if [ ! -f ${SCRIPT_TST_DIR}/$*.chk ] || ${SCRIPT_TST_DIR}/$*.chk; \
+	then \
 	( ${SCRIPT_DIR}/$(shell echo $* | sed -e 's/_[0-9]*$$//') $< \
 	| ${buffer_output} ) 2>&1 \
 	| ${filter_perl_messages} \
 	| diff ${OUTPUT_DIR}/$*.out - > $@ ; \
-	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
+	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi \
+	else \
+	touch $@; \
+	fi
 
 ${OUTPUT_DIR}/%.diff: ${SCRIPT_TST_DIR}/%${OPT} ${COMPILED_MODULES}
 	-@printf "%-30s " "$<:" ; \
+	if [ ! -f ${SCRIPT_TST_DIR}/$*.chk ] || ${SCRIPT_TST_DIR}/$*.chk; \
+	then \
 	( ${SCRIPT_DIR}/$(shell echo $* | sed -e 's/_[0-9]*$$//') \
 	     $(shell grep -v '^#' ${word 1, $^}) \
 	| ${buffer_output} ) 2>&1 \
 	| ${filter_perl_messages} \
 	| diff ${OUTPUT_DIR}/$*.out - > $@ ; \
-	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
+	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi \
+	else \
+	touch $@; \
+	fi
 
 ${OUTPUT_DIR}/%.out: ${SCRIPT_TST_DIR}/%${INP} ${SCRIPT_TST_DIR}/%${OPT} ${COMPILED_MODULES}
 	-@test -f $@ || echo "$@:"
